#-------------------------------------------------------------------------------------------#
# Ansible Playbook for RHGS
# 2019 - romuald@redhat.com 
#-------------------------------------------------------------------------------------------#
- name: Install RHGS SMB Support
  become: yes
  yum: 
    name: "@RH-Gluster-Samba-Server"
    state: latest

- name: Install RHGS SMB AD Integration
  become: yes
  yum: 
    name: "@RH-Gluster-AD-Integration"
    state: latest

- name: Configure firewall (TCP) for SMB
  become: yes
  firewalld: 
    zone: public
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
  with_items: [622,875,2049,2224,3121,20048,21064,32803]

- name: Configure firewall (UDP) for SMB
  become: yes
  firewalld: 
    zone: public 
    port: "{{item}}/udp"
    permanent: true 
    state: enabled
    immediate: yes
  with_items: [662,875,2049,5404,5405,20048,32803,32769]