#-------------------------------------------------------------------------------------------#
# Ansible Playbook for RHGS
# 2019 - romuald@redhat.com 
#-------------------------------------------------------------------------------------------#

## use this role to prepare the system with subscription manager, enabling required repositories
## and do a yum upgrade
##
## usage: -e "sysprep=yes"
- hosts: "{{ host }}"
  gather_facts: false

  pre_tasks:
    - pause:
        prompt: "RHN username"
      when: sysprep == 'yes'
      register: rhn_user
    - pause:
        prompt: "RHN password"
        echo: no
      when: sysprep == 'yes'
      register: rhn_pass
    - pause:
        prompt: "RHN Pool ID"
      when: sysprep == 'yes'
      register: rhn_pool
  roles:
  - role: roles/sysprep
    when: sysprep == 'yes'

## use this role to install the minimum Red Hat Gluster Storage Group packages, configure firewall,
## enable & start the services and peer the 
## the nodes to create the cluster.
- hosts: "{{ host }}"
  gather_facts: false
  roles: 
  - role: roles/rhgs_install
    when: install == 'yes'

## use this role to install the minimum Red Hat Gluster NFS Ganesha with SELINUX, configure firewall,
## and enable & start the services.
- hosts: "{{ host }}"
  gather_facts: false
  roles: 
  - role: roles/rhgs_nfs
    when: nfs == 'yes'

## use this role to install the minimum Red Hat Gluster SMB with AD integration, configure firewall,
## and enable & start the services.
- hosts: "{{ host }}"
  gather_facts: false
  roles: 
  - role: roles/rhgs_smb
    when: smb == 'yes'

