#-------------------------------------------------------------------------------------------#
# Ansible Playbook for RHGS
# 2019 - romuald@redhat.com 
#-------------------------------------------------------------------------------------------#
- hosts: dev
  gather_facts: false

  tasks:

  - name: Install RHGS
    become: yes
    yum:
      name: "redhat-storage-server"
      state: latest

  - name: Install RHGS SMB Support
    become: yes
    yum: 
      name: "@RH-Gluster-Samba-Server"
      state: latest

  - name: Install RHGS SMB AD Integration
    become: yes
    yum: 
      name: "@RH-Gluster-AD-Integration"
      state: latest
