#-------------------------------------------------------------------------------------------#
# Ansible Playbook for RHGS
# 2019 - romuald@redhat.com 
#-------------------------------------------------------------------------------------------#

- name: Install RHGS NFS Ganesha Support
  yum: 
    name: "glusterfs-ganesha,nfs-ganesha-selinux"
    state: latest

- name: Edit sysconfig nfs file for statd ports 
  ignore_errors: true
  shell: "sed -i '/STATD_PORT/s/^{{ '#' }}//' /etc/sysconfig/nfs"
  register: status

- name: Restart NFS & RPC services
  service:
    name: nfs-config,rpc-statd
    state: restarted

- name: Stop NFS Server
  service:
    name: nfs-server
    state: stopped

- name: Disable NFS Server
  service:
    name: nfs-server
    enabled: no

- name: Configure firewall (TCP) for NFS Ganesha
  firewalld: 
    zone: public
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
  with_items: [622,875,2049,2224,3121,20048,21064,32803]
  when: firewalld == "yes"

- name: Configure firewall (UDP) for NFS Ganesha
  firewalld: 
    zone: public 
    port: "{{item}}/udp"
    permanent: true 
    state: enabled
    immediate: yes
  with_items: [662,875,2049,5404,5405,20048,32803,32769]
  when: firewalld == "yes"

 