#-------------------------------------------------------------------------------------------#
# Ansible Playbook for RHGS
# 2019 - romuald@redhat.com 
#-------------------------------------------------------------------------------------------#
- name: Verify if host is already registered 
  become: yes
  ignore_errors: true
  shell: "subscription-manager status"
  register: status

- name: Subscribe to RHN
  become: yes
  redhat_subscription: username={{ RHN_username }} password={{ RHN_password }} pool={{ RHN_poolname }}
  when: status.rc|int > 0

- name: Disable Repositories 
  become: yes
  rhsm_repository:
    name: "*"
    state: disabled
  
- name: Enable Repositories
  become: yes
  rhsm_repository: 
    name: "rhel-7-server-rpms,rhel-7-server-optional-rpms,rhel-7-server-extras-rpms,rh-gluster-3-for-rhel-7-server-rpms,rh-gluster-3-samba-for-rhel-7-server-rpms,rh-gluster-3-samba-for-rhel-7-server-rpms,rh-gluster-3-nfs-for-rhel-7-server-rpms,rhel-ha-for-rhel-7-server-rpms"
    state: enabled
    
- name: Update system
  become: yes
  yum:
    name: "*"
    state: latest

## todo 
# add hostnames to hosts file 
# generate a ssh key and copy over all nodes 
# define a rhel release to be fixed on with "releasever"