#-------------------------------------------------------------------------------------------#
# Ansible Playbook for RHGS
# 2019 - romuald@redhat.com 
#-------------------------------------------------------------------------------------------#

- name: Verify if host is already registered 
  become: yes
  ignore_errors: true
  shell: "subscription-manager status"
  register: status

- debug:
    msg: "Logging in as {{ rhn_user }} with pool {{ rhn_pool }}" 
  when: status.rc|int > 0

- name: Subscribe to RHN
  become: yes
  redhat_subscription: username={{ rhn_user }} password={{ rhn_pass }} pool={{ rhn_pool }}
  when: status.rc|int > 0

- name: Disable Repositories 
  become: yes
  rhsm_repository:
    name: "*"
    state: disabled
  
- name: Enable Repositories
  become: yes
  rhsm_repository: 
    name: "rhel-7-server-rpms,rhel-7-server-optional-rpms,rhel-7-server-extras-rpms,rh-gluster-3-for-rhel-7-server-rpms,rhel-ha-for-rhel-7-server-rpms"
    state: enabled
    
- name: Update system
  become: yes
  yum:
    name: "*"
    state: latest

## todo 
# add hostnames to hosts file 
# generate a ssh key and copy over all nodes 
# define a rhel release to be fixed on with "releasever"
# add conditional for Satellite and related tasks
